name: Copy folder content recursively to remote
on: [push]
        uses: garygrossgarten/github-action-scp@release
        with:
          local: src
          remote: scp/var/www/dev/html
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          rmRemote: true
