
name: scp copy folder to remote via SSH

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      LOCAL: test
    steps:      
      - name: parent working directory
        run: pwd
      - name: list folder contents
        run: ls /home/runner/work/4-year-plan/4-year-plan 
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/4-year-plan/4-year-plan/src
          remote: /var/www/dev/html
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          rmRemote: true
